[package]
name = "md_light"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
reqwest = "0.11.18"
router = "0.6.0"
serde = "1.0.181"
serde_json = "1.0.104"
tera = "1.19.0"
