[package]
name = "md_light"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.6.2"
actix-web = "4.3.1"
chrono = "0.4.26"
clap = { version = "4.3.19", features = ["derive"] }

# anyhow = "1.0.72"
# mangadex = "0.1.2"
maud = "0.25.0"
reqwest = { version = "0.11.18", features = ["blocking"] }
serde = "1.0.181"
serde_json = "1.0.104"
# tera = "1.19.0"
# tokio = { version = "1.29.1", features = ["full"] }
